// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from "next/dynamic";

export const components = {
  case_results: dynamic(() => import("./CaseResults")),
  appointment_form: dynamic(() => import("./AppointmentForm")),
  faq: dynamic(() => import("./Faq")),
  gridimagelist: dynamic(() => import("./Gridimagelist")),
  gridimagetext: dynamic(() => import("./Gridimagetext")),
  home_carousel: dynamic(() => import("./HomeCarousel")),
  homepage_large_image: dynamic(() => import("./HomepageLargeImage")),
  imagebar: dynamic(() => import("./Imagebar")),
  info_panel_row: dynamic(() => import("./InfoPanelRow")),
  logo_bar: dynamic(() => import("./LogoBar")),
  process_steps: dynamic(() => import("./ProcessSteps")),
  reviews: dynamic(() => import("./Reviews")),
  text: dynamic(() => import("./Text")),
  text_image: dynamic(() => import("./TextImage")),
};
